# Generated by Django 3.2.8 on 2021-10-19 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_familyphoto_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyphoto',
            options={'ordering': ['-date_added']},
        ),
    ]
